[template]
include = ["README.md", "Cargo.toml", ".gitignore", "src/", ".cargo/"]
ignore = ["LICENSE"]

[placeholders.ahash-key]
type = "string"
prompt = "What is the ahash key of program that will load this module ?"
default = "[1, 2, 3, 4]"
