[package]
name = "{{crate_name}}"
version = "0.1.0"
edition = "2021"
authors = ["{{authors}}"]

# Remove the library type that you do not want.
crate-type = ["cdylib", "dylib"]

[dependencies]
rhai = { version = "1.10" }
